REQUIRED:
  JOB_NAME: ""
  JOB_PASSWD: newk8s666
  UPLOAD_DIR: fna_det
  PROJECT_ID: AR5019102 # AR5019102 TEAM-ALGORITHM-RD2
  WORKER_MIN_NUM: 1
  WORKER_MAX_NUM: 1
  GPU_PER_WORKER: 8
  RUN_SCRIPTS: ${WORKING_PATH}/scripts/k8s_job.sh

OPTIONAL:
  PRIORITY: 5   #[1-5], highest:5
  DOCKER_IMAGE: docker.hobot.cc/dlp/mxnet:runtime-cudnn7.3-cuda9.2-centos7
  # DOCKER_IMAGE: docker.hobot.cc/dlp/mxnet:runtime-py3.6-cudnn7.4-cuda10.0-centos7
  WALL_TIME: 2880 # 1440  10080 max run minutes: default 7200 = 5days
  REMARK: "added for test. " # string or a filename
